Blocked revisions 70364 via svnmerge
........
  r70364 | eric.smith | 2009-03-14 07:57:26 -0400 (Sat, 14 Mar 2009) | 17 lines
  
  Issue 5237, Allow auto-numbered replacement fields in str.format() strings.
  
  For simple uses for str.format(), this makes the typing easier. Hopfully this
  will help in the adoption of str.format().
  
  For example:
  'The {} is {}'.format('sky', 'blue')
  
  You can mix and matcth auto-numbering and named replacement fields:
  'The {} is {color}'.format('sky', color='blue')
  
  But you can't mix and match auto-numbering and specified numbering:
  'The {0} is {}'.format('sky', 'blue')
  ValueError: cannot switch from manual field specification to automatic field numbering
  
  Will port to 3.1.
........


git-svn-id: http://svn.python.org/projects/python/branches/release26-maint@70365 6015fed2-1504-0410-9fe1-9d1591cc4771